MauvilleCity_CalebsNursery_MapScripts::
	.byte 0

MauvilleCity_CalebsNursery_EventScript_Cori::
	msgbox MauvilleCity_CalebsNursery_Text_CoriGreeting, MSGBOX_NPC
	end

MauvilleCity_CalebsNursery_Text_CoriGreeting:
	.string "Halellujiah… Halellujiah… Hallelu…JAH!\n"
	.string "Whoa, you scared me there!\p"
	.string "Hi, I'm Cori!\n"
	.string "Some days I help out in my big\l"
	.string "brother's shop.$"
